scheduler_level: 3
jobs:
- id: smoke_job
  enabled: true
  scheduler_level: 1
  weekday: 0
  hour: 16
  minute: 21
  command: echo smoke
- id: ui_add_test2
  enabled: true
  command: echo hello2
  weekday: null
  hour: 0
  minute: 0
  scheduler_level: 3
- id: test
  enabled: true
  command: test
  weekday: null
  hour: 0
  minute: 0
  schedule:
    weekday: null
    hour: 0
    minute: 0
  scheduler_level: 3
- id: ui_smoke2
  enabled: true
  command: echo hi
  weekday: null
  hour: 0
  minute: 0
  scheduler_level: 3
